name: shadcn_flutter
description: "Beautifully designed components from Shadcn/UI is now available for Flutter"
version: 0.0.52
homepage: "https://github.com/sunarya-thito/shadcn_flutter"
documentation: "https://sunarya-thito.github.io/shadcn_flutter/"
repository: "https://github.com/sunarya-thito/shadcn_flutter"
issue_tracker: "https://github.com/sunarya-thito/shadcn_flutter/issues"

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.32.3"

dependencies:
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  web: ^1.1.1
  data_widget: ^0.0.3
  gap: ^3.0.1
  expressions: ^0.2.5+2
  animation_kit: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

topics:
  - widgets
  - user-interface
  - design
  - components
  - shadcn-ui
